import React, { useRef, useState } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { LayoutGrid, Plus, Upload, Loader2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { LAYOUTS } from '@/lib/uncefact/layout';
import { extractInvoiceDataFromPdf } from '@/lib/uncefact/pdf';

export default function Templates() {
  const navigate = useNavigate();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isExtracting, setIsExtracting] = useState(false);

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      setIsExtracting(true);
      const arrayBuffer = await file.arrayBuffer();
      const extractedData = await extractInvoiceDataFromPdf(arrayBuffer);
      
      if (extractedData) {
        // Navigate to editor with the extracted data
        navigate('/editor', { state: { importedData: extractedData } });
      } else {
        alert("Could not find embedded PDF/A-3 JSON-LD metadata in this file.");
      }
    } catch (error) {
      console.error(error);
      alert("Failed to parse the PDF file.");
    } finally {
      setIsExtracting(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = ''; // Reset input
      }
    }
  };

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold">Templates</h1>
          <p className="text-gray-500">Choose a starting point for your invoice.</p>
        </div>
        <Button onClick={() => navigate('/editor')}>
          <Plus className="w-4 h-4 mr-2" />
          Create From Scratch
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
        {LAYOUTS.map((layout) => (
          <Card key={layout.id} className="hover:shadow-md transition-shadow">
            <CardHeader>
              <div className="w-10 h-10 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center mb-4">
                <LayoutGrid className="w-6 h-6" />
              </div>
              <CardTitle>{layout.name}</CardTitle>
              <CardDescription>{layout.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-sm space-y-1">
                <div className="flex justify-between">
                  <span className="text-gray-500">Country:</span>
                  <span>{layout.countryCode}</span>
                </div>
                 <div className="flex justify-between">
                  <span className="text-gray-500">Style:</span>
                  <span>{layout.font.heading.split('-')[0]}</span>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button 
                variant="outline" 
                className="w-full" 
                onClick={() => navigate('/editor', { state: { layoutId: layout.id } })}
              >
                Use Template
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      {/* Import Section */}
      <div className="border-t pt-12">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-2xl font-bold mb-4">Import Existing Document</h2>
          <p className="text-gray-500 mb-8">
            Upload an existing PDF/A-3 invoice generated by TradeDocs. We will automatically extract the embedded JSON-LD metadata and populate the editor for you.
          </p>
          
          <input 
            type="file" 
            accept="application/pdf" 
            className="hidden" 
            ref={fileInputRef}
            onChange={handleFileUpload}
          />
          
          <Button 
            size="lg" 
            className="w-full sm:w-auto"
            onClick={() => fileInputRef.current?.click()}
            disabled={isExtracting}
          >
            {isExtracting ? (
              <><Loader2 className="w-5 h-5 mr-2 animate-spin" /> Extracting Data...</>
            ) : (
              <><Upload className="w-5 h-5 mr-2" /> Upload PDF/A-3 File</>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
